config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root "top#index"
 get 'about' => 'top#show_us'
 get 'contact' => 'top#show_contact'
 get 'contents' => 'top#show'
 get '0' => 'top#show_0'
 get '1' => 'top#show_1'
 get '2' => 'top#show_2'
 get '3' => 'top#show_3'
 
 scope ':chapter_number' do
   resources :questions do
       resources :replies, only: [:index]
   end
 end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  
  belongs_to :user
  has_many   :replies
  
end

app/models/reply.rb
class Reply < ApplicationRecord

  belongs_to  :question

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :questions
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def index
    @questions = Question.where(chapter_number: params[:chapter_number]).page(params[:page]).per(5)
    render "index_#{params[:chapter_number]}"
  end
  
  def new
    @question = Question.new
  end
  
  def show
    @question = Question.find(params[:id])
    @replies = @question.replies
  end
    
  def create
    Question.create(chapter_number: params[:chapter_number], text: question_params[:text], user_id: current_user.id)
  end
  
  private
  def question_params
    params.require(:question).permit(:chapter_number, :text, :user_id)
  end
  
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

 def index
     question = Question.where(id: params[:id])
     @replies = question.replies
 end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

 before_action :authenticate_user!, only: [:show, :show_0, :show_1, :show_2]
 
 def index
 end

 def show_us
 end
 
 def show_contact
 end

 def show
 end
 
 def show_0
 end

 def show_1
 end
 
 def show_2
 end
 
 def show_3
 end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>Finance2.0</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <div id="wrapper">
      <header class="header">
        <div class="inner clearfix">
          <div class="headerTtl clearfix">
            <h1>
              <a href="/">
                金融教育2.0
              </a>
            </h1>
          </div>
          <div class="headerNavi clearfix">
            <ul class="navvar">
              <li>
                <a href="/contents">Contents</a>
              </li>
              <li>
                <a href="/about">About us</a>
              </li>
              <% if user_signed_in? %>
                <li>
                  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
                </li>
              <% else %>
                <li>
                  <a href="/users/sign_in">ログイン</a>
                </li>
                <li>
                  <a href="/users/sign_up">新規登録</a>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </header>

    <%= yield %>
    
      <footer class="footer">
        <p>© 2021 金融教育2.0, Inc.</p>
      </footer>
    </div>

  </body>
  
</html>

app/views/questions/create.html.erb
<div class="top-view-contents-row">
  <h2>質問を送信しました！</h2>
  <br>
  <h2>質問の回答には最大で１週間程お時間を頂きます。</h2>
  <br>
  <h2>回答をご準備しております間、<br>ぜひその他の章をお読み頂ければ幸いです。</h2>
  
  <div class="go-to-contents-button">
    <%= link_to "Contentsへ戻る", contents_path, method: :get, class: "go-to-contents-button-li" %>
  </div>
</div>

app/views/questions/index_0.html.erb
<div class="questions-index-title">
  <h2 class="Qtitle">「Chapter_0 手段と目的」について、これまで頂いた質問</h2>
</div>

<div class="contents-row">
  <% @questions.each do |question| %>
    <div class="Question">
      <div class="Q-icon">
         <h2 class="Q">Q</h2>
      </div>
      <div class="Q-text">
        <div class="text">
          <p><%= question.text %></p>  
        </div>
        <div class="reply-button">
          <%= link_to 'この質問に対する回答を見る ▶︎', "/#{question.chapter_number}/questions/#{question.id}", method: :get, class: "reply-button-li" %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="pagination">
    <h3><%= paginate(@questions) %></h3>
  </div>
  <br>
</div>

app/views/questions/index_1.html.erb
<div class="questions-index-title">
  <h2 class="Qtitle">「Chapter_1 リスクとリターン」について、これまで頂いた質問</h2>
</div>

<div class="contents-row">
  <% @questions.each do |question| %>
    <div class="Question">
      <div class="Q-icon">
         <h2 class="Q">Q</h2>
      </div>
      <div class="Q-text">
        <div class="text">
          <p><%= question.text %></p>  
        </div>
        <div class="reply-button">
          <%= link_to 'この質問に対する回答を見る ▶︎', "/#{question.chapter_number}/questions/#{question.id}", method: :get, class: "reply-button-li" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/questions/index_2.html.erb
<div class="questions-index-title">
  <h2 class="Qtitle">「Chapter_2 投資と投機①」について、これまで頂いた質問</h2>
</div>

<div class="contents-row">
  <% @questions.each do |question| %>
    <div class="Question">
      <div class="Q-icon">
         <h2 class="Q">Q</h2>
      </div>
      <div class="Q-text">
        <div class="text">
          <p><%= question.text %></p>  
        </div>
        <div class="reply-button">
          <%= link_to 'この質問に対する回答を見る ▶︎', "/#{question.chapter_number}/questions/#{question.id}", method: :get, class: "reply-button-li" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/questions/index_3.html.erb
<div class="questions-index-title">
  <h2 class="Qtitle">「Chapter_3 投資と投機②」について、これまで頂いた質問</h2>
</div>

<div class="contents-row">
  <% @questions.each do |question| %>
    <div class="Question">
      <div class="Q-icon">
         <h2 class="Q">Q</h2>
      </div>
      <div class="Q-text">
        <div class="text">
          <p><%= question.text %></p>  
        </div>
        <div class="reply-button">
          <%= link_to 'この質問に対する回答を見る ▶︎', "/#{question.chapter_number}/questions/#{question.id}", method: :get, class: "reply-button-li" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/questions/new.html.erb
<div class="top-view-contents-row">
  <h2>下記質問を送信します。よろしいですか？</h2>
  <div class="attention">
    <p>※現在まだ質問の確認画面をご用意出来ておらず、１クリックで送信されます。</p>
    <p>※質問内容につきましては、ご確認の上、送信をお願いします。</p>
  </div>
  
  <div class="form">
    <div class="form-inner">
      <%= form_for @question, url: { action: "create" } do |f| %>
        <div class="form-group-2">
          <%= f.label :text, "ご質問内容" %><br/>
          <%= f.text_area :text, rows: 10, class: 'form-control-2' %><br/>
          <div class="submit-button">
            <%= f.submit '                                             送信                                             ' %>
          </div>
        </div>   
      <% end %>
    </div>
  </div>

</div>

app/views/questions/show.html.erb
<div class="Question-show">
    <div class="Q-icon">
      <h2 class="Q">Q</h2>
    </div>
    <div class="Q-text">
      <div class="text">
        <p><%= @question.text %></p>
      </div>
    </div>
</div>

<% @replies.each do |reply| %>
    <div class="Replies">
      <div class="A-icon">
        <h2 class="A">A</h2>
      </div>
      <div class="A-text-area">
        <div class="A-text">
          <p><%= reply.text %></p>
        </div>
      </div>
    </div>
<% end %>

<% if @replies.empty? %>
  <div class="Replies">
    <p>この質問に対する回答は現在準備中です。</p>
  </div>
<% end %>

<div class="replies-notification">
  <p>回答に対する追加ご質問の画面をまだご用意出来ておりませんため、<br>追加のご質問は再度別にご質問を頂ければ幸いです。<br>よろしくお願いします。</p>
</div>

<div class="go-to-contents-button">
    <%= link_to "Contentsへ戻る", contents_path, method: :get, class: "go-to-contents-button-li" %>
</div>

app/views/top/_show_0.html.erb
<p>Chapter_0 手段と目的</p>

<div class="contents-row">
  <%= form_with model: @question do |form| %>
     <%= form.text_field :text %>
     <%= form.submit %>
  <% end %>
</div>

<div class="contents-row">
  <% @questions.each do |question| %>
    <p><%= question.user.nickname %>さんの質問</p>
    <p><%= question.text %></p>
  <% end %>
</div>

app/views/top/index.html.erb
<div class="site-title-sub">
  <h2 class="heading">未来に駆ける</h2>  
</div>

<div class="top-view-contents-title">
  <h2>マネーリテラシーの低い国、日本</h2>
</div>


<div class="top-view-contents">
  <p>2012年にマスターカード社が行った調査では、なんとアジア最下位。</p>
  <p>インターネットの色々なコンテンツが普及したとはいえ、現在もそれ程大きく状況は変わっていません。</p>
  <p>むしろ日本国内の金融情報に対する規制はより厳しくなっているかもしれません。</p>
  <p>このような現実をあなたはご存知でしょうか？</p>
  <br>
  <a href="https://newsroom.mastercard.com/asia-pacific/ja/press-releases/newsroom-120719/">MasterCard調査：アジア/太平洋地域の財務リテラシー指標調査</a>
  <br>
  <br>
  <p>知らなくても仕方がありません。</p>
  <p>なぜなら日本には金融カリキュラムが通常の学校教育では一切ないのです。</p>
  <br>
  <p>今の私達は決して、多くの祖先と同じやり方で資産形成をすることは出来ません。</p>
  <p>もしあなたが、資産形成に対する取り組みを今それ程なされていないなら。</p>
  <p>あるいは、ご自身で金融に対する体系的な知識をお持ちでないと感じるなら。</p>
  <p>このコンテンツを是非よく読んで頂きたいです。</p>
  <br>
  <p>社会人の方向けに書きましたが、高校生以上の方でしたら、是非読んで頂きたいです。</p>
  <p>事実アメリカでは、この金融に対する教育が高校のカリキュラムに入っているのです。</p>
  <p>そして、我々の愛するこの日本が、お金の知識について実は世界的に低レベルというこの現実。</p>
  <p>これも悔しくないですか？</p>
  <br>
  <p>私は以前、会社組織の中での生き方や方向性に、非常に悩んでいました。</p>
  <p>この知識を知った時、すごい安心感を覚えると同時に、未来を違う方法で描けると確信したのです。</p>
  <p>もしこの世界をまだあまり知らない方だったら、もしかしたら、自分と同じように感じて頂けるかもしれない。</p>
  <p>その思いを込めて、このアプリを作成しました。</p>
  <br>
  <p>このアプリには金融に対する考え方のエッセンスを詰め込みました。</p>
  <p>そういう意味では、非常に詰め込んだ内容になっています。</p>
  <p>一方で大事なポイントは前半に寄せております。</p>
  <br>
  <p>このコンテンツは皆様から質問やご要望を頂き、それに答えられるよう、ログインしてご覧頂く形になります。</p>
  <p>一方で私達が皆様からお金を頂くことは決してありません。</p>
  <p>ぜひ安心して、そして楽しんで学んで頂ければ幸いです。</p>
  <p>それでは始めましょう！</p>
  <div class="go-to-contents-button2">
    <%= link_to "Contentsへ", contents_path, method: :get, class: "go-to-contents-button-li" %>
  </div>
</div>

app/views/top/show.html.erb
<div class="table-of-contents-title">
  <h2>Contents</h2>
</div>


<ul class="table-of-contents">
  <li><%= link_to 'Chapter 0: 手段と目的', '/0', class: "table-of-contents-li" %></li>
  <li><%= link_to 'Chapter 1: リスクとリターン', '/1', class: "table-of-contents-li" %></li>
  <li><%= link_to 'Chapter 2: 投資と投機①', '/2', class: "table-of-contents-li" %></li>
  <li><%= link_to 'Chapter 3: 投資と投機②', '/3', class: "table-of-contents-li" %></li>
</ul>

app/views/top/show_0.html.erb
<div class="site-title-sub-0">
  <h2 class="heading">Chapter_0 手段と目的</h2> 
</div>

<div class="top-view-contents-title">
  <h2>あなたの目的は何ですか？</h2>
</div>

<div class="top-view-contents">
  <p>色々な質問を頂きますが、させて頂く共通の質問があります。</p>
  <br>
  <p>「あなたの目的は何ですか？」</p>
  <br>
  <p>旅行に例えるなら、どこに行こうかという目的地であり、そしてそこで何をするか、ということです。</p>
  <p>そしてその後に、その方法を考えるはず。</p>
  <br>
  <p>日本人はお金や金融に関しては、この順序がひっくり返ることがよくあります。</p>
  <p>例えばビットコイン。それは手段にすぎないのに、最終ゴールが決まってないまま、まず一歩を踏み出してしまう。</p>
  <br>
  <p>金融に関しても、まず、目的を考えることが大切です。例えば、何歳の時にどんな状態になっていたいか、とか。</p>
  <p>勿論未来のことは分からないので、私達の多くは「幸せになっていたい。」と、とりあえず漠然と考えることも多いです。</p>
  <p>幸せの要素にも色々あると思います。家庭だったり、仕事や日々の生活や営みだったり。</p>
  <br>
  <p>このコンテンツではお金を取り上げます。</p>
  <p>日本人はお金に対するイメージがよくないように、戦後から、義務教育などですりこまれています。</p>
  <p>断言します。人生で最も大事なことはお金ではありません。</p>
  <p>一方でお金がやっぱり大切と、今回は一度立ち返って欲しいです。</p>
  <p>自分自身や、自分の大切な人に安心安全な生活を送れるようにする。</p>
  <p>今回はお金と真剣に向き合って欲しいです。</p>
  <p>そしてご自身の生き方や目的を叶える上で、お金になるべく困らないようにするために、どういうアプローチを取るべきか。</p>
  <br>
  <p>例えば検索して見て欲しいです。</p>
  <p>大阪、投資、セミナーとか、ネットで検索すると沢山出てきます。</p>
  <p>そこで出てくるのは、FX、株、不動産、とかっていうのが出て参ります。</p>
  <p>これってあくまでも手段なんですよね。金融のベースの考え方とかは、ほとんどの場合出て来ないです。</p>
  <br>
  <p>投資セミナーなどで、よく見られて良くないなと思うことは、セミナーが終わると、こういう風に言われることです。</p>
  <p>「あなたが今聞いているセミナーを前に聞いた人は１年経った今、こんな風になっています。今あなたが一歩を踏み出せば、あなたの未来も開けます。逆に始めなければ、今のままです。」</p>
  <p>これは心理学的にも結構バイアスがかかることです。</p>
  <p>多くの人がこうなると、「やるか」、「やらないか」の2択になります。</p>
  <p>これは自分もよく経験があるのですが、やるなら１００％、やらないなら全くやらない。という風になりがちです。特に日本人は。</p>
  <br>
  <p>「金融の世界ではリターンが高いものはいつ無くなるか分かりません。」</p>
  <p>この点をよく意識いただいて、本当に、今自分がやろうとしている事は、今のタイミングで合っているのか、よく考えてもらえればと思います。</p>
  <p>次章で「リスクとリターン」について説明します。これは言葉通りの意味なのですが、真の意味で理解されている人はやはり少ないと思っています。</p>
  <p>手段として何を用いるかは、勿論とても大切なのですが、次章から背景になるベースの部分を説明させて頂きます。</p>
  <div class="next-action-button">
    <%= link_to '<< Contentsへ戻る', '/contents', class: "back-to-contents-li" %>
    <%= link_to 'Chapter_1 リスクとリターンへ >>', '/1', class: "next-chapter-li" %>
  </div>
  <br>
  
  <div class="ask-about-questions">
    <h2>質問はございませんか？</h2>
  </div>
  <p>　金融教育2.0では質問がございましたら、回答させて頂きます。</p>
  <br>
  
  <div class="new-question-button">
    <%= link_to '質問を投稿する ▶︎', '/0/questions/new', class: "new-question-button-li" %>
  </div>
  <br>
  <div class="questions-index-button">
    <%= link_to 'これまで頂いた質問はこちら ▶︎', '/0/questions', class: "questions-index-button-li" %>
  </div>
  <br>
</div>

app/views/top/show_1.html.erb
<div class="site-title-sub-0">
  <h2 class="heading">Chapter_1 リスクとリターン</h2> 
</div>

<div class="top-view-contents-title">
  <h2>金融の世界ではリスクとリターンが釣り合っている</h2>
</div>

<div class="top-view-contents">
  <p>金融商品をグルーピングすると、こんな風になります。</p>
  <div class="insert-chart"></div>
  <p>大体大きく３つに分けると、Lowのリスクは不動産とか債権、Middleになると、株とか為替、HighのリスクはFX、仮想通貨という感じになります。</p>
  <p>この中で何のことか分かりませんというものがありましたら、ぜひ質問して下さい。匿名で質問可能です。</p>
  <br>
  <p>リスク３つに対して、商品６個位ありますが、これはあくまで一つの目安です。</p>
  <p>たまに不動産が低いからと言って、とにかく不動産という人もいますが、不動産も選ぶものを間違えれば、リスクはハイになります。</p>
  <p>逆にミドルに対しても、きちんと考えてリスクをコントロールして運用すると、Lowのリスクになったりします。</p>
  <p>選ぶ商品や選ぶものでリスクは変わるのですが、ざっくり分けると、こんな風になります。</p>
  <br>
  <p>一方で、大体、金融とか投資をほとんど知らない人間がアクションを取ろうとすると、まずハイのリスクにある、FXや仮想通貨を見ます。一番上です。</p>
  <p>なぜなら、５年後に資産が倍になると言われるよりも、２ヶ月で倍になると言われた方が嬉しいからです。</p>
  <p>それに引っかかります。自分もそうでした。引っかかってはいないですが、ビットコインすげー！買ってみようかなって思っていました（笑）。</p>
  <br>
  <p>このリスクに対してどういう風に向き合うべきか。これは銀行や証券会社とか、機関投資家とか、金融のプロがしていることを一つモデルにして頂ければと思います。</p>
  <p>そういう人達が何をしているかというと、一番最初にLowの部分を見ます。</p>
  <p>顧客から預かったお金の９９％をLowに置いておきます。</p>
  <br>
  <p>置いておくと、どういうことが起こるかというと、しっかり時間をかけるとキャッシュフローというのが生まれます。</p>
  <p>時間をかけるとLowのリスクでリターンも少ないけれど、確実にキャッシュフローが生まれます。</p>
  <p>そのキャッシュフローをミドルのリスクに上げていっている。</p>
  <p>ミドルのリスクは失うリスクも大きいが失っても、大丈夫。ミドルをやめて、またLowに戻れば良い。</p>
  <p>Lowのベースは残っているはず。</p>
  <div class="insert-chart2"></div>
  <p>ミドルで時間をかけると、また上手くなり、リスクをコントロールして、少しずつキャッシュを上げられるようになる。</p>
  <p>それを更にハイのリスクに上げる。</p>
  <p>端的に言うと、Lowから着実にキャッシュフローを作って、それをリスクの高いもの、すなわちリターンの高いものに少しずつ配分していくのが考え方の基本になります。</p>
  <br>
  <p>個人の人は、全部Lowに入れると良いかというと、そういう訳でもなくて、一部をミドルに入れてバランスを組めば良いかなという風に考えています。</p>
  <p>皆さんが必ずしもこのパーセンテージにすべきという事は、決してないのですが、こちらを一つの目安として提案させて頂きます。</p>
  <p>そしてLowにしっかりと資産を置いて、時間をかけていくと、キャッシュフローが生まれるので、それを少しずつ、ミドルとかハイに上げていく。</p>
  <p>そうすると少しずつ、ミドルやハイの割合が増えていくというのが、まぁ一つの目安になります。</p>
  <div class="insert-chart3"></div>
  <p>これをイメージとして持って頂ければと思っています。</p>
  <p>ですので、今皆さんが資産をどのように持っているか、というのを、ちょっとこれを見ながら考えてもらえると嬉しいです。</p>
  <p>このようにリスクと向き合ってバランスを取ることが資産形成において非常に重要です。</p>
  <br>
  <p>次にポイントになるのが、次章でお話する「投資と投機の違い」を知ることです。</p>
  <div class="next-action-button">
    <%= link_to '<< Contentsへ戻る', '/contents', class: "back-to-contents-li" %>
    <%= link_to 'Chapter_2 投資と投機①へ >>', '/2', class: "next-chapter-li" %>
  </div>
  <br>
  
  <div class="ask-about-questions">
    <h2>質問はございませんか？</h2>
  </div>
  <p>　金融教育2.0では質問がございましたら、回答させて頂きます。</p>
  <br>
  <div class="new-question-button">
    <%= link_to '質問を投稿する▶', '/1/questions/new', class: "new-question-button-li" %>
  </div>
  <br>
  <div class="questions-index-button">
    <%= link_to 'これまで頂いた質問はこちら ▶︎', '/1/questions', class: "questions-index-button-li" %>
  </div>
  <br>
</div>

app/views/top/show_contact.html.erb
<p>Contact us</p>

app/views/top/show_us.html.erb
<div class="site-title-sub-about">
  <h2 class="heading">About us</h2>
</div>

<div class="top-view-contents-title">
  <h2>私達について</h2>
</div>

<div class="top-view-contents">
  <p>この世界を知っているかどうかで、お金の使い方だけでなく、人生の時間の使い方も大きく変わる。</p>
  <p>それがはっきりと分かった今、友人達とも相談しながら、このアプリの開発・公開を始めました。</p>
  <br>
  <p>私がこの世界に初めて触れたのは、29歳、20代の最後の年でした。</p>
  <p>大学時代に親しかった、ある友人と、ひょんな事で再会したことがきっかけでした。</p>
  <br>
  <p>勿論、今後の資本主義がどうなるかとか、世界の格差がどうなるかとか、そういったことは分かりませんし、</p>
  <p>自分達の投資が上手く行くかどうかも、言ってしまえば、100%は分からないのが正直な所です。</p>
  <br>
  <p>一方で、この知識が誰かの何かの決断のための一つの材料となり、またその人の背中を押すことになればと思っています。</p>
  <p>そして、その可能性を信じ、今後もコンテンツを充実させて行きたいと思っています。</p>
  <br>
  <p>今後はLINE@なども設け、一部の方々からの直接の問い合わせにも対応出来る仕組みを導入予定です。</p>
  <p>そちらでは、定期的に実施しておりますセミナーなどもご案内させて頂く予定です。</p>
  <br>
  <p>セミナーは、このアプリのコンテンツに近い内容なのですが、face to faceなど、より近い形でのご説明になります。</p>
  <p>セミナーは一部有料となりますが、決して高額なものではありません。</p>
  <p>また、昨今のコロナウイルスに対する懸念により、ZoomなどのWeb会議システムでの実施となる場合もございます。</p>
  <br>
  <p>また、私達が具体的にどのような金融商品に投資しているか、そちらについても、直接問い合わせ頂ければ、具体的にお話させて頂きます。</p>
  <p>そちらについては、このアプリのコンテンツでも今後少しずつ触れて行くつもりではおります。</p>
  <p>具体的な商品のご紹介に当たり、私達が皆様からお金を頂くことは決してありませんので、その点もご安心して頂ければ幸いです。</p>
  <br>
  <p>まだ始めたばかりの試みであり、至らない点も多々あるかと存じますが、今後とも、何卒よろしくお願いします。</p>
  <br>
  <br>
</div>